name: Check Pull Request Opened

on:
  # pull_request:
  #   types: [opened, edited, reopened, synchronize]

  schedule:
    - cron: '*/2 * * * *'

jobs:
  get_pr_open:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get active pull requests
        id: active_prs
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls?state=open

      - name: Print active pull requests
        run: |
          echo "Active pull requests:"
          echo "${{ steps.active_prs.outputs.data }}" 

  # pr_duration:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}=${{ hashFiles('**/yarn.lock') }}

      - name: Get Pull Request date
        id: pr_info
        run: |
          echo "::set-output name=created::$(jq -r '.pull_request.created_at' $GITHUB_EVENT_PATH)"
          echo "::set-output name=number::$(jq -r '.number' $GITHUB_EVENT_PATH)"
        
      # - name: Display Pull Request Info
      #   run: |
      #     echo "Pull request number is ${{ steps.pr_info.outputs.number }}"
      #     echo "Pull request created at ${{ steps.pr_info.outputs.created }}"

      - name: Check PR duration
        run: |
          created_at=$(date -d "$(echo "${{ steps.pr_info.outputs.created }}" | tr -d 'Z')" +%s)
          now=$(date +%s)
          duration=$(echo "(${now} - ${created_at})/(60)" | bc)
          echo "PR has been open for ${duration} minutes."
