name: Check Open Pull Requests

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  check_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get open pull requests
        id: open_prs
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls?state=open
      
      - name: Print pull requests
        run: |
          echo "Open pull requests:"
          echo "${{ steps.open_prs.outputs.data }}"
