name: Check Open Pull Requests

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  # schedule:
  #   - cron: '*/1 * * * *'

jobs:
  pr_duration:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}=${{ hashFiles('**/yarn.lock') }}

      - name: Get active pull requests
        id: active_prs
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls?state=open

      - name: Check pull request age
        run: |
          echo "Checking Pull Request age..."
          # echo "$PULL_REQUESTS"
          for pr in $PULL_REQUESTS; do
            echo "PR: $pr"
          done
        shell: bash
        env:
          PULL_REQUESTS: ${{ steps.active_prs.outputs.data }}

