name: Check Pull Request

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  pr_duration:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}=${{ hashFiles('**/yarn.lock') }}

      - name: Get Pull Request date
        id: pr_info
        run: |
          echo "::set-output name=created::$(jq -r '.pull_request.created_at' $GITHUB_EVENT_PATH)"
          echo "::set-output name=number::$(jq -r '.number' $GITHUB_EVENT_PATH)"
        
      - name: Display Pull Request Info
        run: |
          echo "Pull request number is ${{ steps.pr_info.outputs.number }}"
          echo "Pull request created at ${{ steps.pr_info.outputs.created }}"

      # - name: Checkout code
      #   uses: actions/checkout@v2
      # - name: Get PR data
      #   run: echo "::set-env name=pr_created::$(jq -r '.pull_request.created_at' $GITHUB_EVENT_PATH) ::set-env name=pr_number::$(jq -r '.number' $GITHUB_EVENT_PATH)"
      #   id: pr
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Wait for PR to close
      #   id: duration
      #   uses: chrislennon/wait-for-pull-request-action@v1
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     pull-request-number: ${{ env.pr_number }}
      # - name: Print duration
      #   run: echo "PR #${{ env.pr_number }} was open for ${{ steps.duration.outputs.duration }}."
